const PREFIX='ranasports-'+self.registration.scope;
const CACHE=PREFIX+'v46';
const BUILD='20260917-2037';
const CORE=['./','./index.html','./noticia.html','./assets/styles.css','./assets/redesign.css','./assets/portal-list.css','./assets/app.js','./assets/fresh-news-gate.js','./assets/sportscore-competition-filter.js','./assets/scoreboard-events.js','./assets/live-fix.js','./assets/live-animations.js','./assets/header-socials.js','./assets/navigation.js','./assets/highlights.js','./assets/breaking.js','./assets/hot-topics-v2.js','./assets/live-scores.js','./assets/trends.json','./assets/news-feed.js','./assets/icon.svg','./assets/icon-192.png','./assets/icon-512.png','./assets/apple-touch-icon.png','./manifest.webmanifest','./noticias/bienvenidos.html','./noticias/agenda-deportiva.html','./noticias/rana-f1.html','./legal/acerca-de.html','./legal/contacto.html','./legal/privacidad.html'];
const coreURLs=new Set(CORE.map(path=>new URL(path,self.registration.scope).href));
const APP_URL=new URL('./assets/app.js',self.registration.scope).href;
const NEWS_GATE_URL=new URL('./assets/fresh-news-gate.js',self.registration.scope).href;
const FILTER_URL=new URL('./assets/sportscore-competition-filter.js',self.registration.scope).href;
const EVENTS_URL=new URL('./assets/scoreboard-events.js',self.registration.scope).href;
const LIVE_FIX_URL=new URL('./assets/live-fix.js',self.registration.scope).href;
const LIVE_ANIM_URL=new URL('./assets/live-animations.js',self.registration.scope).href;
const HEADER_SOCIALS_URL=new URL('./assets/header-socials.js',self.registration.scope).href;
const NEWS_CSV_HOST='docs.google.com';
const NEWS_CSV_PATH='/spreadsheets/d/e/2PACX-1vRmbZPf_uxPdpS-phGua9U3PccA2z7Uls3G8r49CLfi37qkMJkpRPDUU7VdAZg_IMI7Ynegy-yxyAhr/pub';
const STATUS_COLOR_FIX=`(()=>{if(document.querySelector('#rs-status-color-fix'))return;const s=document.createElement('style');s.id='rs-status-color-fix';s.textContent='.rs-st.live,.rs-st.finished{color:#ff1746!important}html[data-theme="light"] .rs-lgh,html[data-theme="light"] .rs-lgn,html[data-theme="light"] .rs-lgh>span{color:#171b21!important}html[data-theme="light"] .rs-st{background:#fff!important;border-right-color:#cfd6df!important}html[data-theme="light"] .rs-st.upcoming{color:#59636e!important}html[data-theme="light"] .rs-st.live,html[data-theme="light"] .rs-st.finished{color:#ff1746!important}html[data-theme="light"] .rs-st.postponed{color:#a66300!important}';document.head.append(s)})();`;
async function freshResponse(url){const target=new URL(url);target.searchParams.set('_rsbuild',BUILD);return fetch(target.href,{cache:'reload',credentials:'same-origin'});}
async function combinedApp(cache){try{const[appResponse,gateResponse,filterResponse,eventsResponse,fixResponse,animResponse,socialResponse]=await Promise.all([freshResponse(APP_URL),freshResponse(NEWS_GATE_URL),freshResponse(FILTER_URL),freshResponse(EVENTS_URL),freshResponse(LIVE_FIX_URL),freshResponse(LIVE_ANIM_URL),freshResponse(HEADER_SOCIALS_URL)]);if(!appResponse.ok)throw new Error('app '+appResponse.status);const appText=await appResponse.text(),gateText=gateResponse.ok?await gateResponse.text():'',filterText=filterResponse.ok?await filterResponse.text():'',eventsText=eventsResponse.ok?await eventsResponse.text():'',fixText=fixResponse.ok?await fixResponse.text():'',animText=animResponse.ok?await animResponse.text():'',socialText=socialResponse.ok?await socialResponse.text():'';const headers=new Headers(appResponse.headers);headers.set('content-type','application/javascript; charset=utf-8');headers.delete('content-length');headers.delete('content-encoding');const merged=new Response(appText+'\n\n/* RanaSports fresh news gate v46 */\n'+gateText+'\n\n/* RanaSports SportScore competition guard v46 */\n'+filterText+'\n\n/* RanaSports goal/red-card enhancer v46 */\n'+eventsText+'\n\n/* RanaSports scoreboard v46 */\n'+fixText+'\n\n/* RanaSports live animations v46 */\n'+animText+'\n\n/* RanaSports header socials v46 */\n'+socialText+'\n\n/* RanaSports status and contrast fix */\n'+STATUS_COLOR_FIX,{status:200,statusText:'OK',headers});await cache.put(APP_URL,merged.clone());return merged;}catch(error){const cachedApp=await cache.match(APP_URL),cachedGate=await cache.match(NEWS_GATE_URL),cachedFilter=await cache.match(FILTER_URL),cachedEvents=await cache.match(EVENTS_URL),cachedFix=await cache.match(LIVE_FIX_URL),cachedAnim=await cache.match(LIVE_ANIM_URL),cachedSocial=await cache.match(HEADER_SOCIALS_URL);if(cachedApp){return new Response((await cachedApp.text())+'\n'+(cachedGate?await cachedGate.text():'')+'\n'+(cachedFilter?await cachedFilter.text():'')+'\n'+(cachedEvents?await cachedEvents.text():'')+'\n'+(cachedFix?await cachedFix.text():'')+'\n'+(cachedAnim?await cachedAnim.text():'')+'\n'+(cachedSocial?await cachedSocial.text():'')+'\n'+STATUS_COLOR_FIX,{headers:{'content-type':'application/javascript; charset=utf-8'}});}return Response.error();}}
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE);await Promise.all(CORE.map(async path=>{const canonical=new URL(path,self.registration.scope).href;try{const response=await freshResponse(canonical);if(response.ok)await cache.put(canonical,response.clone());}catch{}}));await self.skipWaiting();})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith(PREFIX)&&key!==CACHE).map(key=>caches.delete(key)));await self.clients.claim();const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const client of clients){try{await client.navigate(client.url);}catch{}}})()));
self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(event.request.method!=='GET')return;if(url.hostname===NEWS_CSV_HOST&&url.pathname===NEWS_CSV_PATH&&url.searchParams.get('output')==='csv'){const fresh=new URL(url.href);fresh.searchParams.set('_rs',Date.now().toString());event.respondWith(fetch(fresh.href,{cache:'no-store',credentials:'omit'}));return;}if(url.origin!==self.location.origin||!url.href.startsWith(self.registration.scope))return;const normalized=new URL(url.href);normalized.search='';if(!coreURLs.has(normalized.href))return;event.respondWith((async()=>{const cache=await caches.open(CACHE);if(normalized.href===APP_URL)return combinedApp(cache);try{const response=await freshResponse(normalized.href);if(response.ok&&response.type==='basic')event.waitUntil(cache.put(normalized.href,response.clone()));return response;}catch{return(await cache.match(normalized.href))||Response.error();}})());});